# Generated by Django 5.1.4 on 2025-11-11 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pelicula',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('director_name', models.CharField(max_length=50)),
                ('synopsis', models.IntegerField()),
                ('release_year', models.DateField()),
            ],
        ),
    ]
