# Generated by Django 5.1.4 on 2025-11-11 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='pelicula',
            new_name='Movie',
        ),
    ]
